trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
  - task: PackerBuild@1
    displayName: 'Build a Packer Image'
    inputs:
      templateType: 'custom'
      customTemplateLocation: 'windowsimage.json'
